/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'websiteUrl' : string,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'eventDateEnd' : [] | [string],
  'category' : string,
  'rating' : number,
  'location' : string,
  'eventDate' : [] | [string],
}
export type AuthResult = { 'ok' : UserPublic } |
  { 'err' : string };
export type DirectResetPasswordResult = { 'ok' : null } |
  { 'err' : string };
export type FavoriteResult = { 'ok' : null } |
  { 'err' : string };
export type GetMeResult = { 'ok' : UserPublic } |
  { 'err' : string };
export type UpdateUserResult = { 'ok' : UserPublic } |
  { 'err' : string };
export type UserId = bigint;
export interface UserPublic {
  'id' : UserId,
  'createdAt' : bigint,
  'email' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface _SERVICE {
  'addFavorite' : ActorMethod<[bigint], FavoriteResult>,
  'forgotPassword' : ActorMethod<
    [string, string, string],
    DirectResetPasswordResult
  >,
  'getActivities' : ActorMethod<[], Array<Activity>>,
  'getActivitiesByCityAndState' : ActorMethod<
    [string, string],
    Array<Activity>
  >,
  'getActivitiesByCityStateAndCategory' : ActorMethod<
    [string, string, string],
    Array<Activity>
  >,
  'getActivity' : ActorMethod<[bigint], [] | [Activity]>,
  'getByCategory' : ActorMethod<[string], Array<Activity>>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getMe' : ActorMethod<[], GetMeResult>,
  'getWeekendEventsByCityAndState' : ActorMethod<
    [string, string, [] | [string]],
    Array<Activity>
  >,
  'login' : ActorMethod<[string, string], AuthResult>,
  'logout' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[string, string, string, string], AuthResult>,
  'removeFavorite' : ActorMethod<[bigint], FavoriteResult>,
  'searchActivities' : ActorMethod<[string], Array<Activity>>,
  'updateUser' : ActorMethod<[string, string, string], UpdateUserResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];