/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FavoriteResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const DirectResetPasswordResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'eventDateEnd' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
  'eventDate' : IDL.Opt(IDL.Text),
});
export const UserId = IDL.Nat;
export const UserPublic = IDL.Record({
  'id' : UserId,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const GetMeResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
export const AuthResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
export const UpdateUserResult = IDL.Variant({
  'ok' : UserPublic,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([IDL.Nat], [FavoriteResult], []),
  'forgotPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [DirectResetPasswordResult],
      [],
    ),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getActivitiesByCityAndState' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getActivitiesByCityStateAndCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getActivity' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
  'getByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getMe' : IDL.Func([], [GetMeResult], ['query']),
  'getWeekendEventsByCityAndState' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'logout' : IDL.Func([], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AuthResult],
      [],
    ),
  'removeFavorite' : IDL.Func([IDL.Nat], [FavoriteResult], []),
  'searchActivities' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UpdateUserResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FavoriteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const DirectResetPasswordResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Text,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'eventDateEnd' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
    'eventDate' : IDL.Opt(IDL.Text),
  });
  const UserId = IDL.Nat;
  const UserPublic = IDL.Record({
    'id' : UserId,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const GetMeResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
  const AuthResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
  const UpdateUserResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([IDL.Nat], [FavoriteResult], []),
    'forgotPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [DirectResetPasswordResult],
        [],
      ),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getActivitiesByCityAndState' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivitiesByCityStateAndCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivity' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
    'getByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getMe' : IDL.Func([], [GetMeResult], ['query']),
    'getWeekendEventsByCityAndState' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'logout' : IDL.Func([], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'removeFavorite' : IDL.Func([IDL.Nat], [FavoriteResult], []),
    'searchActivities' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UpdateUserResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };