/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = bigint;
export type DirectResetPasswordResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Activity {
    id: bigint;
    websiteUrl: string;
    name: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    eventDateEnd?: string;
    category: string;
    rating: number;
    location: string;
    eventDate?: string;
}
export interface UserPublic {
    id: UserId;
    createdAt: bigint;
    email: string;
    lastName: string;
    firstName: string;
}
export type FavoriteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type GetMeResult = {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
};
export type AuthResult = {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
};
export type UpdateUserResult = {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
};
export interface backendInterface {
    addFavorite(activityId: bigint): Promise<FavoriteResult>;
    forgotPassword(email: string, newPassword: string, confirmPassword: string): Promise<DirectResetPasswordResult>;
    getActivities(): Promise<Array<Activity>>;
    getActivitiesByCityAndState(city: string, state: string): Promise<Array<Activity>>;
    getActivitiesByCityStateAndCategory(city: string, state: string, category: string): Promise<Array<Activity>>;
    getActivity(id: bigint): Promise<Activity | null>;
    getByCategory(category: string): Promise<Array<Activity>>;
    getFavorites(): Promise<Array<bigint>>;
    getMe(): Promise<GetMeResult>;
    getWeekendEventsByCityAndState(city: string, state: string, currentDate: string | null): Promise<Array<Activity>>;
    login(email: string, password: string): Promise<AuthResult>;
    logout(): Promise<void>;
    register(firstName: string, lastName: string, email: string, password: string): Promise<AuthResult>;
    removeFavorite(activityId: bigint): Promise<FavoriteResult>;
    searchActivities(searchQuery: string): Promise<Array<Activity>>;
    updateUser(firstName: string, lastName: string, email: string): Promise<UpdateUserResult>;
}
import type { Activity as _Activity, AuthResult as _AuthResult, DirectResetPasswordResult as _DirectResetPasswordResult, FavoriteResult as _FavoriteResult, GetMeResult as _GetMeResult, UpdateUserResult as _UpdateUserResult, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFavorite(arg0: bigint): Promise<FavoriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return from_candid_FavoriteResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return from_candid_FavoriteResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async forgotPassword(arg0: string, arg1: string, arg2: string): Promise<DirectResetPasswordResult> {
        if (this.processError) {
            try {
                const result = await this.actor.forgotPassword(arg0, arg1, arg2);
                return from_candid_DirectResetPasswordResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forgotPassword(arg0, arg1, arg2);
            return from_candid_DirectResetPasswordResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivitiesByCityAndState(arg0: string, arg1: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesByCityAndState(arg0, arg1);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesByCityAndState(arg0, arg1);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivitiesByCityStateAndCategory(arg0: string, arg1: string, arg2: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesByCityStateAndCategory(arg0, arg1, arg2);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesByCityStateAndCategory(arg0, arg1, arg2);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivity(arg0: bigint): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getByCategory(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getByCategory(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getByCategory(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getMe(): Promise<GetMeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe();
                return from_candid_GetMeResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe();
            return from_candid_GetMeResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeekendEventsByCityAndState(arg0: string, arg1: string, arg2: string | null): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeekendEventsByCityAndState(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeekendEventsByCityAndState(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3);
                return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3);
            return from_candid_AuthResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFavorite(arg0: bigint): Promise<FavoriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return from_candid_FavoriteResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return from_candid_FavoriteResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchActivities(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchActivities(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchActivities(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string): Promise<UpdateUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2);
                return from_candid_UpdateUserResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2);
            return from_candid_UpdateUserResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Activity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DirectResetPasswordResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DirectResetPasswordResult): DirectResetPasswordResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_FavoriteResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FavoriteResult): FavoriteResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_GetMeResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetMeResult): GetMeResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateUserResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateUserResult): UpdateUserResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Activity]): Activity | null {
    return value.length === 0 ? null : from_candid_Activity_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    websiteUrl: string;
    name: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    eventDateEnd: [] | [string];
    category: string;
    rating: number;
    location: string;
    eventDate: [] | [string];
}): {
    id: bigint;
    websiteUrl: string;
    name: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    eventDateEnd?: string;
    category: string;
    rating: number;
    location: string;
    eventDate?: string;
} {
    return {
        id: value.id,
        websiteUrl: value.websiteUrl,
        name: value.name,
        tags: value.tags,
        description: value.description,
        imageUrl: value.imageUrl,
        eventDateEnd: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.eventDateEnd)),
        category: value.category,
        rating: value.rating,
        location: value.location,
        eventDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.eventDate))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n5(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
